### PR TITLE
Add some basic tests for telegram events

### PR DESCRIPTION
**Pull request by xrmx**
So one can refactor this part with some confidence of not breaking stuff

### CODE REVIEW

**Comment by Mte90** [comment]
I like the idea, so we do some tests to our telepot wrapper.

**Comment by xrmx** [comment]
Will take a look later today to see why python3.6 does not see the tests module, works fine on 3.8 locally.

**Comment by Mte90** [comment]
The python command works but not the github action @xrmx https://github.com/MozillaItalia/mozitahub_bot/runs/1285971806

I think that is a bug in the github action that not download the repository so cannot run anything. I will fix it now.

**Comment by Mte90** [comment]
Indeed is now working as you can see, GH action don't download the repo automatically

**Pull request merged**
